### ISSUE TITLE
Let's talk: Useful mod metadata entries

### ISSUE THREAD

**Issue by 0xJoeMama** [Felis-Project/felis#6]
Kind of connected with #2.
There is a mods.toml schema refactor on the horizon, so I'd like some idea for what can go in there.
The current implementation was a quick-and-dirty way to get some mod-loading started.
As of now, it has not proven to be a problem, but mod dependencies are about to change that.
Since I'll be changing the schema, might as well completely refactor it.
SO...give me some ideas for useful entries and/or entry refactoring.

**Comment by JR1811** [comment]
I think at least...

- Authors / Developers
- Contact / Website(s)
- Official Distributed Platforms
- Issue tracker link

... could be interesting?

**Comment by 0xmycf** [comment]
- synopsis of the mod?
- Licence
---

- (favourite cat)

**Comment by 0xJoeMama** [comment]
> - synopsis of the mod?

So like a description? That's already in there.
Unless you mean add like a slogan as wellas the existing description, in which case I'm on board.

> - license

oh so yes

**Comment by 0xJoeMama** [comment]
I will *soon-ish* release a schema here. Be on the lookout.

**Comment by 0xJoeMama** [comment]
First schema implementation [3aa9531](https://github.com/Felis-Project/felis/commit/3aa95312a00389656ed1c7d5ba84bfa886e1b765)

**Comment by 0xJoeMama** [comment]
This is the final version of schema v1:
https://github.com/Felis-Project/felis/blob/1676c151014f1e2fe6844ba7645dfa492461e9e3/src/main/kotlin/felis/meta/ModMetadataSchemaV1.kt

**Comment by 0xJoeMama** [comment]
Closed by 1.5.0-alpha which implements the above schema.
